### ISSUE TITLE
Auto-detect the GRASS path?

### ISSUE THREAD

**Issue by Robinlovelace** [rsbivand/rgrass#64]
As described by Vero in the FOSS4G conference the following command in the shell returns GRASS's data path:

```
grass --config path
/usr/lib/grass80
```

Worth auto detecting this?

**Comment by florisvdh** [comment]
I think that would be interesting; was also mentioned by @veroandreo in https://github.com/rsbivand/rgrass/issues/29#issuecomment-866021930.

It depends on `grass` being available in the system PATH though; may not work in each situation?

**Comment by rsbivand** [comment]
Please also see https://lists.osgeo.org/pipermail/grass-stats/2022-August/001857.html

**Comment by rsbivand** [comment]
In released 0.3-5 on CRAN now, thanks!
