### ISSUE TITLE
Prepare migration from **XML** to **xml2**

### ISSUE THREAD

**Issue by rsbivand** [rsbivand/rgrass#72]
The **XML** package may face retirement and IFAIK is not actively maintained. It would be very hepful to consider how to migrate to **xml2**. Fixes to **XML** have only been made to keep up with changes in the underlying external library for several years. **XML** uses **Rcurl** which is similarly vulnerable; **xml2** uses **curl**, both are actively maintained.

**Comment by rsbivand** [comment]
See https://gist.github.com/nuest/3ed3b0057713eb4f4d75d11bb62f2d66

**Comment by florisvdh** [comment]
@rsbivand I think this one is implemented completely? (in which case it can be closed)
